<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$qrCode = isset($specificInfo['qr_code']) ? $specificInfo['qr_code']: null;
$qrCodeImage = isset($specificInfo['qr_code_image']) ? $specificInfo['qr_code_image'] : null;
$expirationDateQrcode = $specificInfo['expiration_date_qrcode'];
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="getnet-instruction pix">
        <div class="instruction-information expiration">
            <div>
                <?= $block->escapeHtml(__('Your payment is valid until')); ?>
            </div>
            <div class="expiration-date">
                <strong>
                    <?= /* @noEscape */ $block->formatDate($expirationDateQrcode, \IntlDateFormatter::MEDIUM, true) ?>
                </strong>
            </div>
        </div>
        <?php if ($qrCodeImage): ?>
            <div class="instruction-information qr-code-image">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('To pay, read the QRCode')); ?>
                </div>
                <div class="qrcode-image">
                    <img src="<?=  $block->escapeHtml($qrCodeImage) ?>" alt="<?= /* @noEscape */ $title ?>" />
                </div>
            </div>
        <?php endif;?>
        <?php if ($qrCode): ?>
            <div class="instruction-information qr-code">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Or if you prefer, copy and paste the code')); ?>
                </div>
                <div class="qrcode-text">
                    <textarea id="qr-code-value"
                        rows="10" cols="30" readonly><?= $block->escapeHtml($qrCode) ?></textarea>
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif;?>
