<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$qrCode = isset($specificInfo['qr_code']) ? $specificInfo['qr_code']: null;
$qrCodeImage = isset($specificInfo['qr_code_image']) ? $specificInfo['qr_code_image'] : null;
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="getnet-instruction wallet">
        <?php if ($qrCodeImage): ?>
            <div class="instruction-information qr-code-image">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('To pay, read the QRCode')); ?>
                </div>
                <div class="qrcode-image">
                    <img src="<?=  $block->escapeHtml($qrCodeImage) ?>" alt="<?= /* @noEscape */ $title ?>" />
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif;?>