name: 🐞 Reportar um Erro
description: Problema técnico no módulo ou na integração
title: "[Bug]: "
labels: ["Bug","Needs Triage"]
assignees:
  - elisei
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este relatório de bug!
  - type: input
    id: contact
    attributes:
      label: Detalhes de contato
      description: Como podemos entrar em contato com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Conte-nos também, o que você esperava que acontecesse e qual foi o resultado obtido!
      placeholder: Conte-nos qual foi o resultado obtido!
      value: "Aconteceu um bug!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão do Magento
      description: E qual a versão do seu magento?
      options:
        - 2.3.x (Magento >= 2.3.0 e < 2.4.0)
        - 2.4.x (Magento >= 2.4.0)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: O problema pode ter alguma relação com um navegador específico?
      multiple: true
      options:
        - Não tem relação com o navegador usado
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Há logs relavantes sobre o problema?
      description: Copie e cole qualquer saída de log relevante. Isso será formatado automaticamente em código, portanto, não há necessidade de backticks.
      placeholder: Caso esteja ativo, o nosso log fica em var/log/payment.log, considere também enviar o var/log/exception.log
      render: shell
  - type: checkboxes
    id: privacy
    attributes:
      label: Meu log não contém informações confidênciais
      description: Ao reportar esse problema, estou ciente que não há nenhuma violação de privacidade nos dados enviados no log fornecido acima
      options:
        - label: Eu não estou enviando dados que viole a privacidade do cliente ou da loja.
          required: true
  - type: dropdown
    id: Severity
    attributes:
      label: Qual a severidade do problema?
      multiple: true
      options:
        - A loja ficou fora do ar
        - Nenhum cliente consegue realizar um pagamento
        - Uma das formas de pagamento não está funcionando
        - Eu não consegui instalar o módulo
        - Eu não consegui configurar o módulo
    validations:
      required: true
