name: Solicitação de Novo Recurso
description: Descreve recursos que deseja ver no módulo
title: "[Feature]: "
labels: ["feature request", "triage"]
assignees:
  - elisei
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para nos contar o que deseja ver no módulo.
  - type: input
    id: contact
    attributes:
      label: Detalhes de contato
      description: Como podemos entrar em contato com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: O que você gostaria que módulo tivesse?
      description: Diga-nos o qual recurso vocẽ deseja que módulo tenha.
      value: "Qual é o comportamento esperado desse recurso, como ele vai funcionar?"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão do Magento
      description: E qual a versão do seu magento?
      options:
        - 2.3.x (Magento >= 2.3.0 e < 2.4.0)
        - 2.4.x (Magento >= 2.4.0)
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Meu log não contém informações confidênciais
      description: Ao reportar esse problema, estou ciente que não há nenhuma violação de privacidade nos dados enviados no log fornecido acima
      options:
        - label: Eu não estou enviando dados que viole a privacidade do cliente ou da loja.
          required: true