<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccInstallment = $block->getInfoData('cc_installment');
?>
<fieldset class="admin__fieldset payment-method" 
    id="payment_form_<?= /* @noEscape */ $code ?>" 
    data-url-to-tokenize="<?= $block->escapeHtml($block->getUrlForTokenize()); ?>" style="display: none;">
    <input type="hidden"
        name="payment[is_active_payment_token_enabler]" />
    <input type="hidden" 
        id="<?= /* @noEscape */ $code ?>_number_token"
        name="payment[cc_number_token]"
        value="<?= /* @noEscape */ $block->getInfoData('cc_number_token') ?>"/>
    <?php if ($block->getTaxDocumentCapture()): ?>
        <div class="field-text required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_holder_tax_document">
                <span><?= $block->escapeHtml(__('Credit Card Holder Tax Document')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Tax Document')) ?>"
                       class="required-entry admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_holder_tax_document"
                       name="payment[cc_holder_tax_document]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_holder_tax_document') ?>"/>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->getPhoneCapture()): ?>
        <div class="field-text required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_holder_phone">
                <span><?= $block->escapeHtml(__('Credit Card Holder Phone')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Phone')) ?>"
                       class="required-entry admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_holder_phone"
                       name="payment[cc_holder_phone]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_holder_phone') ?>"/>
                <div class="admin__field-note">
                    <span><?= /* @noEscape */ __('Format: (99)99999-9999') ?></span>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div class="field-text required admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cardholde_name">
            <span><?= $block->escapeHtml(__('Credit Card Holder Full Name')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Full Name')) ?>"
                   class="required-entry admin__control-text"
                   id="<?= /* @noEscape */ $code ?>_cardholde_name"
                   name="payment[cc_cardholder_name]"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_holder_fullname') ?>"/>
        </div>
    </div>
    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_type">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_type" name="payment[cc_type]"
                    class="required-entry validate-cc-type-select admin__control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtml($typeCode) ?>"
                            <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_number">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_number" name="payment[cc_number]"
                   title="<?= $block->escapeHtml(__('Credit Card Number')) ?>"
                   class="admin__control-text validate-cc-number"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr" 
                    name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cid">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                        name="payment[cc_cid]"
                        class="required-entry validate-cc-cvn admin__control-cvn admin__control-text"
                        id="<?= /* @noEscape */ $code ?>_cid"
                        value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Select Instalmment')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_installments" name="payment[cc_installments]"
                        class="admin__control-select required-entry">
                <?php foreach ($block->getSelectInstallments() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $ccInstallment): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</fieldset>
<script>
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('{$code}');
    });
    require(["Getnet_PaymentMagento/js/tokenize"], function () {
    });
</script>