<!--
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */
-->
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>">
    <div class="admin__field">
        <label class="admin__field-label"><span><?= $escaper->escapeHtml(__('Instruction')) ?></span></label>
        <div class="admin__field-control checkmo-mailing-address">
            <?= /* @noEscape */ nl2br($escaper->escapeHtml($block->getInstruction())) ?>
        </div>
    </div>
</fieldset>

<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . $escaper->escapeJs($block->getMethodCode())
) ?>
