<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccInstallment = $block->getInfoData('cc_installment');
?>
<fieldset class="admin__fieldset payment-method" 
    id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" 
    style="display: none;">
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_method_type">
            <span><?= $block->escapeHtml(__('Select card type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_method_type" name="payment[wallet_card_type]"
                        class="admin__control-select required-entry">
                    <option value="credit">
                        <?= $block->escapeHtml(__('Credit')) ?>
                    </option>
                    <option value="debit">
                        <?= $block->escapeHtml(__('Debit')) ?>
                    </option>
            </select>
        </div>
    </div>

    <div class="field-text required admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_payer_phone">
            <span><?= $block->escapeHtml(__('Mobile')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" title="<?= $block->escapeHtml(__('Mobile')) ?>"
                   class="required-entry admin__control-text"
                   id="<?= /* @noEscape */ $code ?>_payer_phone"
                   name="payment[wallet_payer_phone]"
                   value="<?= /* @noEscape */ $block->getInfoData('wallet_payer_phone') ?>"/>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_method_type">
            <span><?= $block->escapeHtml(__('Select card type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_method_type" name="payment[cc_installments]"
                        class="admin__control-select required-entry">
                    <?php foreach ($block->getSelectInstallments() as $k => $v): ?>
                        <option value="<?= $block->escapeHtml($k) ?>"
                                <?php if ($k == $ccInstallment): ?>selected="selected"<?php endif ?>>
                            <?= $block->escapeHtml($v) ?>
                        </option>
                    <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="admin__field">
        <label class="admin__field-label"><span><?= $block->escapeHtml(__('Instruction')) ?></span></label>
        <div class="admin__field-control checkmo-mailing-address">
            <?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstruction())) ?>
        </div>
    </div>
</fieldset>