<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$getpayLink = isset($specificInfo['getpay_link']) ? $specificInfo['getpay_link']: null;
// phpcs:ignore Generic.Files.LineLength
$getpayLexpirationDate = isset($specificInfo['getpay_expiration_date']) ? $specificInfo['getpay_expiration_date'] : null;
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="getnet-instruction boleto">
        <?php if ($getpayLexpirationDate): ?>
        <div class="instruction-information expiration">
            <div>
                <?= $block->escapeHtml(__('Your payment is valid until')); ?>
            </div>
            <div class="expiration-date">
                <strong>
                    <?= /* @noEscape */ $block->formatDate($getpayLexpirationDate, \IntlDateFormatter::MEDIUM, true) ?>
                </strong>
            </div>
        </div>
        <?php endif;?>
        <?php if ($getpayLink): ?>
            <div class="instruction-information link">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Link to Pay')); ?>
                </div>
                <div class="boleto-link">
                    <a target="_blank"
                        href="<?=  $block->escapeHtml($getpayLink) ?>" 
                        alt="<?= /* @noEscape */ $title ?>"><?= $block->escapeHtml(__('Pay Here')); ?></a>
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif;?>
